//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreQuery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScoreQuery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string @__EVENTARGUMENT {
            get {
                return ResourceManager.GetString("__EVENTARGUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string @__EVENTTARGET {
            get {
                return ResourceManager.GetString("__EVENTTARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %2FwEWBALtgYX0DwK%2Fycb4AQLU6rEHAuLjh4YMJ%2FuMbOy0%2Ffn0UeHoB5DIxlisz08%3D.
        /// </summary>
        internal static string @__EVENTVALIDATION {
            get {
                return ResourceManager.GetString("__EVENTVALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %2FwEPDwUKMTUwODM3MTQ2Nw9kFgICAQ9kFgICCQ8PFgQeBFRleHRlHgdWaXNpYmxlaGRkZGO0jC0dS0YidkgEu6HHtZzJ4QnM.
        /// </summary>
        internal static string @__VIEWSTATE {
            get {
                return ResourceManager.GetString("__VIEWSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;btnSelect=%E6%9F%A5%E8%AF%A2&amp;__EVENTVALIDATION=%2FwEWCgKKurKkCQKC5sFXApf3trkEAtjpwosFAoD60dMBAo%2F6pfQIAoD6pfQIAo%2F6iQkCgPqJCQLax9vVBtD771fvr%2F4hhpjHMxYIAWKmKsY%2F.
        /// </summary>
        internal static string TermPostData_Footer {
            get {
                return ResourceManager.GetString("TermPostData_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __EVENTTARGET=&amp;__EVENTARGUMENT=&amp;__VIEWSTATE=%2FwEPDwUKLTM1MDcwMDg1MQ9kFgICAQ9kFgICAQ9kFghmD2QWAmYPZBYCAgMPDxYEHgRUZXh0BQzlrablubTlrabmnJ8eB0VuYWJsZWRoZGQCAQ9kFgJmD2QWAgIBDxAPFgYeDURhdGFUZXh0RmllbGQFCFRlcm1OYW1lHg5EYXRhVmFsdWVGaWVsZAUIWWVhclRlcm0eC18hRGF0YUJvdW5kZ2QQFQYV4oCU4oCU6K%2B36YCJ5oup4oCU4oCUFjIwMTctMjAxOOWtpuW5tDHlrabmnJ8WMjAxNi0yMDE35a2m5bm0MuWtpuacnxYyMDE2LTIwMTflrablubQx5a2m5pyfFjIwMTUtMjAxNuWtpuW5tDLlrabmnJ8WMjAxNS0yMDE25a2m5bm0MeWtpuacnxUGATAFMjAxNzEFMjAxNjIFMjAxNjEFMjAxNTIFMjAxNTEUKwMGZ2dnZ2dn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TermPostData_Header {
            get {
                return ResourceManager.GetString("TermPostData_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnSelect=%E6%9F%A5%E8%AF%A2&amp;RdbCourse=%E4%B8%AA%E4%BA%BA%E8%80%83%E8%AF%95%E8%A1%A8&amp;__EVENTVALIDATION=%2FwEWEwKnosvNCQLekp65DQKA%2BtHTAQKP%2BqX0CAKA%2BqX0CAKP%2BokJAoD6iQkCj%2FqdogsCgPqdogsCj%2FrhxgICgPrhxgICj%2Fr1mwoCgPr1mwoCj%2FrZvAUCgPrZvAUC2sfb1QYCuaHTqAgCj%2FnpnQ4CwZTn4wjTLfcvTVfX55m%2FAmiFXqb6s67%2FEQ%3D%3D.
        /// </summary>
        internal static string TestPostData_Footer {
            get {
                return ResourceManager.GetString("TestPostData_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __EVENTTARGET=&amp;__EVENTARGUMENT=&amp;__LASTFOCUS=&amp;__VIEWSTATE=%2FwEPDwULLTE2NTU5MjUyNDUPZBYCAgEPZBYCAgEPZBYEAgEPZBYCZg9kFgQCAQ8QZBAVDgnor7fpgInmi6kFMjAxNzEFMjAxNjIFMjAxNjEFMjAxNTIFMjAxNTEFMjAxNDIFMjAxNDEFMjAxMzIFMjAxMzEFMjAxMjIFMjAxMjEFMjAxMTIFMjAxMTEVDgnor7fpgInmi6kFMjAxNzEFMjAxNjIFMjAxNjEFMjAxNTIFMjAxNTEFMjAxNDIFMjAxNDEFMjAxMzIFMjAxMzEFMjAxMjIFMjAxMjEFMjAxMTIFMjAxMTEUKwMOZ2dnZ2dnZ2dnZ2dnZ2dkZAIIDxBkZBYBZmQCBA9kFgJmD2QWAmYPPCsACwBkZG%2Bxh4GjYLWaC9xSbhtbEWSA%2BPUM.
        /// </summary>
        internal static string TestPostData_Header {
            get {
                return ResourceManager.GetString("TestPostData_Header", resourceCulture);
            }
        }
    }
}
